---
title: "Update Merged Dataset After MotionQC and Coverage Check"
date: "`r format(Sys.time(), '%B %d, %Y')`"
author: "Isaac Chen"

format: 
    html:
      toc: true
      embed-resources: true
---

### Set up

```{r}
#| warning: false
#| message: false

library(here)
library(tidyverse)
library(knitr)
 
# Clear all variables from environment
rm(list = ls())

# Set input files
data_dir         <- here("data", "phenotype")
merged_dir       <- here("data", "phenotype", "merged")
results_dir      <- here("results", "check_missing-coverage")
participants_rds <- here(data_dir, "merged", "merged_participants_motionQC-coverage.rds")
coverage_exclude <- here(results_dir, "froi_coverage_exclude.csv")

# Set output files
output_participants_rds <- here(merged_dir, "merged_participants_motionQC-coverage.rds")
output_participants_csv <- here(merged_dir, "merged_participants_motionQC-coverage.csv")

# Read in data
merged_participants_df <- readRDS(participants_rds) 
coverage_exclude       <- read_csv(coverage_exclude)
```

## Update Sample Size

```{r}
# Extract participants excess (>20%) missing coverage of the fROI
coverage_exclude <- coverage_exclude |> 
  select(unique_id, exclude) |> 
  distinct(unique_id, exclude) |>
  mutate(exclude = "missing >20% coverage for fROI") |> 
  rename(exclude_add = exclude)

# Updated participants csv with those excluded for excess missing coverage
merged_participants_df <- merged_participants_df |> 
  left_join(coverage_exclude, by = "unique_id") |>
  mutate(exclude = ifelse(is.na(exclude), exclude_add, exclude)) |> 
  select(-exclude_add)
```

```{r}
# Print updated sample size
merged_participants_df |> 
  filter(is.na(exclude)) |> 
  glimpse()
```

```{r}
# Save results
saveRDS(merged_participants_df, file = output_participants_rds)
write_csv(merged_participants_df, file = output_participants_csv)
```

## Exclusion summary

:::{.panel-tabset}

### By criteria

```{r}
#| warning: false
#| message: false

# Summary of excluded participants
exclude_table <- merged_participants_df |> 
  filter(!is.na(exclude)) |> 
  group_by(exclude) |> 
  summarize(n = n())

kable(exclude_table)
```

### By dataset & criteria

```{r}
#| warning: false
#| message: false

# Summary of excluded participants
exclude_table <- merged_participants_df |> 
  filter(!is.na(exclude)) |> 
  group_by(dataset, exclude) |> 
  summarize(n = n())

kable(exclude_table)
```

